name: research-pod

services:
  web-api:
    build: 
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=209.38.5.85:9094,209.38.6.221:9094,134.199.141.69:9094
      - FLASK_APP=server:server
      - FLASK_ENV=development
      - FLASK_DEBUG=1