name: research-pod

services:
  web-api:
    build: 
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-controller-0.richardr.dev:9094,kafka-controller-1.richardr.dev:9094,kafka-controller-2.richardr.dev:9094
      - FLASK_APP=server:server
      - FLASK_ENV=development
      - FLASK_DEBUG=1