apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    email: me@richardroberson.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    # Default solver using HTTP-01 challenge for internal services
    - http01:
        ingress:
          class: nginx
      selector:
        dnsZones:
        - "cluster.local"
    # DNS-01 solver for public domains
    - dns01:
        cloudflare:
          email: me@richardroberson.dev
          apiTokenSecretRef:
            name: cloudflare-dns
            key: cloudflare_api_token
      selector:
        dnsZones:
        - "richardr.dev"