resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
  

service:
  type: LoadBalancer
  port: 80
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "kafkaui.richardr.dev"

yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: kafka.default.svc.cluster.local:9092
  auth:
    type: disabled
  # management:
  #   health:
  #     ldap:
  #       enabled: false