resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

service:
  type: LoadBalancer
  port: 80
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "kafkaui.richardr.dev"

volumes:
  - name: kafka-tls
    secret:
      secretName: kafka-tls

volumeMounts:
  - name: kafka-tls
    mountPath: /etc/kafka/certs
    readOnly: true

yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka
        readOnly: true
        bootstrapServers: kafka.default.svc.cluster.local:9092
        ssl:
          enabled: true
          trustStoreLocation: /etc/kafka/certs/kafka-ca.crt
          trustStoreType: PEM
        properties:
          security.protocol: SSL
          ssl.truststore.type: PEM
          ssl.truststore.location: /etc/kafka/certs/kafka-ca.crt
  auth:
    type: disabled