replicaCount: 1

kraft:
  enabled: true

controller:
  replicaCount: 3
  automountServiceAccountToken: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

broker: # Using controller broker nodes instead of separate broker nodes
  automountServiceAccountToken: true

# Configure TLS for all listeners
listeners:
  client:
    protocol: PLAINTEXT
    name: CLIENT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: SSL
    name: EXTERNAL

# TLS Configuration
tls:
  enabled: true
  type: jks
  existingSecret: crt-secret
  jksKeystoreKey: keystore.jks
  jksTruststoreKey: keystore.p12
  passwordsSecret: kafka-jks
  password: "kafka123"
  pemChainIncluded: true
  sslClientAuth: none

externalAccess:
  enabled: true
  broker:
    service:
      type: LoadBalancer
      ports:
        external: 9094
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "{{ .targetPod }}.richardr.dev"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  controller:
    service:
      type: LoadBalancer
      containerPorts:
        external: 9094
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "{{ .targetPod }}.richardr.dev"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  autoDiscovery:
    enabled: true

serviceAccount:
  create: true

rbac:
  create: true

# Enable metrics
# metrics:
#   jmx:
#     enabled: true