namespaceOverride: "monitoring"

grafana:
  adminUser: admin
  adminPassword: prom-operator
  
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

prometheusOperator:
  admissionWebhooks:
    certManager:
      enabled: true
