kokoroTTS:
  replicaCount: 4
  port: 8880
  tag: v0.2.0
  pullPolicy: IfNotPresent
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1

tolerations:
  - key: cloud.google.com/gke-spot
    operator: Equal
    value: "true"
    effect: NoSchedule
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # Requires cert-manager and external-dns to be in the cluster for TLS and DNS
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: koko.richardr.dev
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  hosts:
    - host: koko.richardr.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kokoro-fastapi-tls
      hosts:
        - koko.richardr.dev