replicaCount: 1

image:
  repository: ghcr.io/remsky/kokoro-fastapi-gpu
  tag: v0.2.0
  pullPolicy: IfNotPresent

kokoroTTS:
  repository: ghcr.io/remsky/kokoro-fastapi-gpu
  tag: v0.2.0
  pullPolicy: IfNotPresent
  replicaCount: 2

nodeSelector:
  cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
  cloud.google.com/gke-accelerator-count: "1"

# tolerations:
#   - key: nvidia.com/gpu
#     effect: NoSchedule

service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "koko.richardr.dev"
  


