{{- if .Values.ingress.enabled -}}
{{- $fullName := include "research-cluster.fullname" . }}
{{- $root := . }}
{{- range $i := until (int .Values.replicaCount) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $i }}
  labels:
    {{- include "research-cluster.labels" $root | nindent 4 }}
  {{- with $root.Values.ingress.annotations }}
  annotations:
    {{- tpl (toYaml .) (dict "podIndex" $i "fullName" $fullName) | nindent 4 }}
  {{- end }}
spec:
  {{- with $root.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if $root.Values.ingress.tls }}
  tls:
    {{- range $root.Values.ingress.tls }}
    - hosts:
        - {{ printf "%s-%d.%s" $fullName $i .domain | quote }}
      secretName: {{ printf "%s-%d" .secretName $i }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ printf "%s-%d.%s" $fullName $i $root.Values.ingress.domain | quote }}
      http:
        paths:
          {{- range $root.Values.ingress.paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}-{{ $i }}
                port:
                  number: {{ $root.Values.service.port }}
          {{- end }}
{{- end }}
{{- end }}
